### ISSUE TITLE
Configuration changes tracking issue

### ISSUE THREAD

**Issue by cikzh** [pendulum-project/ntpd-rs#846]
This is a tracking issue to keep track of the changes in configuration. If a change is more work than a simple rename, create a separate issue for it and link it here. Each section corresponds to a TOML section in the config file (with the exception of the CLI section of course)

## logging_observability

-   [x] log_level
-   [x] path -> observation_path
-   [x] mode -> observation_permissions
-   [x] path -> configure_path
-   [x] mode -> configure_permissions

## synchronization

-   [x] min_intersection_survivors -> minimum_agreeing_peers
-   [x] panic_threshold -> single_step_panic_threshold
-   [x] startup_panic_threshold -> startup_step_panic_threshold
-   [x] accumulated_threshold -> accumulated_step_panic_threshold
-   [x] local_stratum

## synchronization.algorithm
-   [x] remove abbreviations
-   [x] jump -> step
-   [x] poll -> poll_interval

## peer_defaults

-   [x] poll_limits -> poll_interval_limits
-   [x] poll_interval -> initial_poll_interval

## peer

-   [x] PeerHostMode
    -   [x] server -> simple
    -   [x] nts_server -> nts
    -   [x] pool
-   [x] ke_addr -> key_exchange_address
-   [x] addr -> address
-   [x] max_peers -> count

## server

-   [x] addr -> listen
-   [x]   denylist_action Ignore - > ignore, Deny -> deny

## nts

-   [x] cert_chain_path -> certificate_chain_path
-   [x] key_der_path -> private_key_path
-   [x] timeout_ms -> key_exchange_timeout_ms
-   [x] addr -> key_exchange_listen

## keyset

-   [x] old_keys -> stale_key_count
-   [x] rotation_interval -> key_rotation_interval
-   [x] storage_path -> key_storage_path

## CLI interface

-   [x] only keep config and log_level
